version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/kalimba
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: ./startup.sh
    depends_on:
      - db 
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'