# Generated by Django 4.2.1 on 2023-06-01 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_rename_votes_guess_votecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(vote.models.VoteType['UP'], 'Upvote'), (vote.models.VoteType['DOWN'], 'Downvote')], max_length=8)),
                ('guess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.guess')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'guess'), name='unique_vote_user_guess'),
        ),
    ]
