# Generated by Django 4.2.1 on 2023-06-01 14:11

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.CharField(choices=[(vote.models.VoteType['UP'], 'Upvote'), (vote.models.VoteType['DOWN'], 'Downvote')], max_length=255),
        ),
    ]
