# Generated by Django 4.2.1 on 2023-06-01 14:43

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=django_mysql.models.EnumField(choices=[('Upvote', 'Up'), ('Downvote', 'Down')]),
        ),
    ]
