# Generated by Django 4.2.1 on 2023-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_created_at_comment_deleted_at_comment_guess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
