# Generated by Django 4.2.1 on 2023-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sample_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='storage/'),
        ),
    ]
