# Generated by Django 4.2.1 on 2023-05-31 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sample_options_alter_sample_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guess',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='samples/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
