# Generated by Django 4.2.1 on 2023-05-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_guess_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sample'),
        ),
    ]
