# Generated by Django 4.2.1 on 2023-06-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comment_guess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='downvotes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='upvotes',
        ),
    ]
