# Generated by Django 4.2.1 on 2023-06-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_downvotes_guess_votes_remove_guess_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='votes',
            new_name='votecount',
        ),
    ]
