name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Install requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: show running container
        run: docker ps
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Migrate
        run: docker exec django_container python manage.py migrate
      - name: Run API Tests
        run: docker exec django_container pytest