name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Install requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  
  migrate:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Migrate
        run: docker exec django_container python manage.py migrate
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  test-api:
    name: Run API tests
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Run API Tests
        run: docker exec django_container pytest