name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Install requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the docker-compose stack
        run: docker-compose up -d
  
  migrate:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Migrate
        run: docker exec django_container python manage.py migrate

  test-api:
    name: Run API tests
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Run API Tests
        run: docker exec django_container pytest